[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CAFAPP_tester"
version = '1.0.0'
description = "Environment for CAFAP tester tools"
readme = "README.md"


dependencies = [
    "datajoint",
    "pandas<2.4",
    "jupyterlab",
    "matplotlib",
    "requests",
    "pathlib",
    "certifi",
    "openpyxl",
    "requests_toolbelt"
]
requires-python = ">=3.13"